version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: lh-opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=false
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      # Persist OpenSearch data to local directory
      - ./opensearch-data:/usr/share/opensearch/data
      # Persist OpenSearch logs
      - ./opensearch-logs:/usr/share/opensearch/logs
    networks:
      - opensearch-net
    restart: unless-stopped

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: lh-opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    depends_on:
      - opensearch
    networks:
      - opensearch-net
    restart: unless-stopped

networks:
  opensearch-net:
    driver: bridge

volumes:
  opensearch-data:
    driver: local